
export const authConstants ={
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FALIURE : 'LOGIN_FALIURE',
    LOGOUT_REQUEST : 'LOGIN_REQUEST'
}

export const userConstants ={
    
    USER_REGISTRATION_REQUEST : 'USER_REGISTRATION_REQUEST',
    USER_REGISTRATION_SUCCESS : 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION__FALIURE : 'USER_REGISTRATION_-FALIURE',
}